# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: raven
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go vet -v ./...
    - go test ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/volck/raven:latest"
      - "ghcr.io/volck/raven:{{.Version}}"
    dockerfile: Dockerfile
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - files/start
archives:
  - format: tar.gz
    id: raven 
    name_template: "raven-{{.Version}}"
    wrap_in_directory: true
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "latest"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
