FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /raven ./cmd/raven/

FROM alpine:latest

RUN apk add --no-cache ca-certificates git openssh-client

ENV CERT_FILE=/mg/secret/ssc/tls.crt \
    CLONE_PATH=/tmp/clone \
    VAULT_TOKEN="" \
    SECRET_ENGINE="" \
    REPO_URL="" \
    SSL_CERT_FILE=/tmp/cert/ca.crt

COPY --from=builder /raven /raven

EXPOSE 8080
USER 1001
ENTRYPOINT ["/raven"]
