FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /logparser ./cmd/logparser/

FROM alpine:latest

RUN apk add --no-cache ca-certificates

ENV LOGPARSER_CONFIG=/etc/raven/logparser.json

COPY --from=builder /logparser /logparser

USER 1001
ENTRYPOINT ["/logparser"]
