apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ssg-a01631-reader
  namespace: a01631
rules:
  - apiGroups:
        - ""
    resources:
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]