# .goreleaser.yml
before:
  hooks:
    - go mod tidy

builds:
  - env: [ "CGO_ENABLED=1" ]
    binary: test
    goos:
    - linux
    goarch:
    - amd64

kos:
  - repository: ghcr.io/volck/raven
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    base: alpine:latest
    sbom: none
    platforms:
    - linux/amd64
